timeout: 1200s
substitutions:
   REGION: us-west1
   CLUSTER:  ugo-prod-cluster
   PROJECTID: yougo-prod-369515
  
steps:
  - name: gcr.io/cloud-builders/kubectl
    id: Configure kubectl
    args:
      - cluster-info
    env:
      - CLOUDSDK_COMPUTE_REGION=$REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$CLUSTER
      - PROJECT_ID=$PROJECTID
      - KUBECONFIG=/workspace/.kube/config
      
  - name: gcr.io/cloud-builders/kubectl
    id: create app secretes
    args: ['apply', '-f', './extras/jwt/jwt-secret.yaml', '--validate=false']
    env:
      - CLOUDSDK_COMPUTE_REGION=$REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$CLUSTER
      - PROJECT_ID=$PROJECTID
      - KUBECONFIG=/workspace/.kube/config
      
  - name: gcr.io/cloud-builders/kubectl
    id: deploy bank-of-anthos
    args: ['apply', '-f', './kubernetes-manifests', '--validate=false']
    env:
      - CLOUDSDK_COMPUTE_REGION=$REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$CLUSTER
      - PROJECT_ID=$PROJECTID
      - KUBECONFIG=/workspace/.kube/config
