timeout: 1200s
substitutions:
   _REGION: us-west1
   _CLUSTER: ugo-dev-cluster
  
steps:
  - name: gcr.io/cloud-builders/kubectl
    id: Configure kubectl
    args:
      - cluster-info
    env:
      - CLOUDSDK_COMPUTE_REGION=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER
      - KUBECONFIG=/workspace/.kube/config
      
  - name: gcr.io/cloud-builders/kubectl
    id: create app secretes
    args: ['apply', '-f', './extras/jwt/jwt-secret.yaml', '--validate=false']
    env:
      - CLOUDSDK_COMPUTE_REGION=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER
      - KUBECONFIG=/workspace/.kube/config
      
  - name: gcr.io/cloud-builders/kubectl
    id: deploy bank-of-anthos
    args: ['apply', '-f', './kubernetes-manifests', '--validate=false']
    env:
      - CLOUDSDK_COMPUTE_REGION=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER
      - KUBECONFIG=/workspace/.kube/config
 
  - name: gcr.io/yougo-k8-hardway-256417/helm
    id: Deploy CPU based HPA
    entrypoint: 'sh'
    args: 
     - '-c'
     - | 
         for val in "balancereader" "contacts" "frontend" "ledgerwriter" "loadgenerator" "transactionhistory" "userservice" ;
            do
              kubectl autoscale deployment $val --cpu-percent=50 --min=1 --max=5
          done
